#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Aleksandr Ptakhin
#
# Install a minimal VM metrics stack on a remote Linux server.
#
# The stack runs Grafana Alloy in Docker, scrapes Linux host metrics via the
# built-in unix exporter, and forwards samples to a hosted Prometheus endpoint.
#
# Required environment variables:
#   DEPLOY_HOST                         - SSH host (IP or hostname)
#   DEPLOY_USER                         - SSH user (must have sudo access)
#   DEPLOY_SSH_KEY                      - Private SSH key contents (not a path)
#   GRAFANA_CLOUD_PROMETHEUS_URL        - Hosted Prometheus remote_write URL
#   GRAFANA_CLOUD_PROMETHEUS_USERNAME   - Hosted Prometheus username / instance ID
#   GRAFANA_CLOUD_PROMETHEUS_PASSWORD   - Hosted Prometheus API key / password
#   GRAFANA_CLOUD_LOKI_URL              - Hosted Loki write URL
#   GRAFANA_CLOUD_LOKI_USERNAME         - Hosted Loki username / instance ID
#   GRAFANA_CLOUD_LOKI_PASSWORD         - Hosted Loki API key / password
#
# Optional environment variables:
#   DEPLOY_PORT                         - SSH port (default: 22)
#   METRICS_DEPLOY_DIR                  - Remote install directory (default: /opt/lalasearch-metrics)
#   VM_METRICS_INSTANCE                 - Instance label (default: DEPLOY_HOST)
#   VM_METRICS_ENVIRONMENT              - Environment label (default: prod)
#   ALLOY_IMAGE_TAG                     - Alloy image tag (default: latest)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
METRICS_SOURCE_DIR="${REPO_ROOT}/infra/metrics"

missing=()
for var in \
    DEPLOY_HOST \
    DEPLOY_USER \
    DEPLOY_SSH_KEY \
    GRAFANA_CLOUD_PROMETHEUS_URL \
    GRAFANA_CLOUD_PROMETHEUS_USERNAME \
    GRAFANA_CLOUD_PROMETHEUS_PASSWORD \
    GRAFANA_CLOUD_LOKI_URL \
    GRAFANA_CLOUD_LOKI_USERNAME \
    GRAFANA_CLOUD_LOKI_PASSWORD; do
    if [[ -z "${!var:-}" ]]; then
        missing+=("$var")
    fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
    echo "Error: missing required environment variables: ${missing[*]}" >&2
    exit 1
fi

DEPLOY_PORT="${DEPLOY_PORT:-22}"
METRICS_DEPLOY_DIR="${METRICS_DEPLOY_DIR:-/opt/lalasearch-metrics}"
VM_METRICS_INSTANCE="${VM_METRICS_INSTANCE:-$DEPLOY_HOST}"
VM_METRICS_ENVIRONMENT="${VM_METRICS_ENVIRONMENT:-prod}"
ALLOY_IMAGE_TAG="${ALLOY_IMAGE_TAG:-latest}"

if [[ ! -f "${METRICS_SOURCE_DIR}/docker-compose.metrics.yml" ]]; then
    echo "Error: metrics compose file not found at ${METRICS_SOURCE_DIR}" >&2
    exit 1
fi

if [[ ! -f "${METRICS_SOURCE_DIR}/config.alloy" ]]; then
    echo "Error: Alloy config not found at ${METRICS_SOURCE_DIR}" >&2
    exit 1
fi

SSH_KEY_FILE="$(mktemp)"
trap 'rm -f "$SSH_KEY_FILE"' EXIT
echo "$DEPLOY_SSH_KEY" > "$SSH_KEY_FILE"
chmod 600 "$SSH_KEY_FILE"

SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o BatchMode=yes -p "$DEPLOY_PORT" -i "$SSH_KEY_FILE")

ssh_cmd() {
    ssh "${SSH_OPTS[@]}" "${DEPLOY_USER}@${DEPLOY_HOST}" "$@"
}

scp_cmd() {
    scp "${SSH_OPTS[@]}" "$@"
}

echo "==> Installing VM metrics to ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PORT}"
echo "    Remote directory: ${METRICS_DEPLOY_DIR}"
echo "    Instance label: ${VM_METRICS_INSTANCE}"
echo "    Environment label: ${VM_METRICS_ENVIRONMENT}"

echo "==> Checking Docker installation..."
ssh_cmd bash -s <<'REMOTE_DOCKER'
set -euo pipefail
if command -v docker &>/dev/null && docker compose version &>/dev/null; then
    echo "Docker and Compose plugin already installed."
else
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "$USER"
    echo "Docker installed. Note: group change takes effect on next login."
fi
REMOTE_DOCKER

echo "==> Creating remote directory..."
ssh_cmd bash -s -- "$METRICS_DEPLOY_DIR" <<'REMOTE_DIR'
set -euo pipefail
METRICS_DEPLOY_DIR="$1"
sudo mkdir -p "$METRICS_DEPLOY_DIR"
sudo chown -R "$USER:$USER" "$METRICS_DEPLOY_DIR"
REMOTE_DIR

echo "==> Uploading metrics stack files..."
scp_cmd \
    "${METRICS_SOURCE_DIR}/docker-compose.metrics.yml" \
    "${METRICS_SOURCE_DIR}/config.alloy" \
    "${DEPLOY_USER}@${DEPLOY_HOST}:${METRICS_DEPLOY_DIR}/"

ENV_CONTENT="$(cat <<ENVEOF
# VM metrics environment - generated by install-vm-metrics.sh
# $(date -u '+%Y-%m-%d %H:%M:%S UTC')
ALLOY_IMAGE_TAG=${ALLOY_IMAGE_TAG}
GRAFANA_CLOUD_PROMETHEUS_URL=${GRAFANA_CLOUD_PROMETHEUS_URL}
GRAFANA_CLOUD_PROMETHEUS_USERNAME=${GRAFANA_CLOUD_PROMETHEUS_USERNAME}
GRAFANA_CLOUD_PROMETHEUS_PASSWORD=${GRAFANA_CLOUD_PROMETHEUS_PASSWORD}
GRAFANA_CLOUD_LOKI_URL=${GRAFANA_CLOUD_LOKI_URL}
GRAFANA_CLOUD_LOKI_USERNAME=${GRAFANA_CLOUD_LOKI_USERNAME}
GRAFANA_CLOUD_LOKI_PASSWORD=${GRAFANA_CLOUD_LOKI_PASSWORD}
VM_METRICS_INSTANCE=${VM_METRICS_INSTANCE}
VM_METRICS_ENVIRONMENT=${VM_METRICS_ENVIRONMENT}
ENVEOF
)"

echo "==> Writing remote environment file..."
echo "$ENV_CONTENT" | ssh_cmd "cat > ${METRICS_DEPLOY_DIR}/.env.metrics"

echo "==> Starting metrics stack..."
ssh_cmd bash -s -- "$METRICS_DEPLOY_DIR" <<'REMOTE_UP'
set -euo pipefail
METRICS_DEPLOY_DIR="$1"
cd "$METRICS_DEPLOY_DIR"
docker compose --env-file .env.metrics -f docker-compose.metrics.yml pull
docker compose --env-file .env.metrics -f docker-compose.metrics.yml up -d
REMOTE_UP

echo "==> Verifying metrics stack..."
ssh_cmd bash -s -- "$METRICS_DEPLOY_DIR" <<'REMOTE_VERIFY'
set -euo pipefail
METRICS_DEPLOY_DIR="$1"
cd "$METRICS_DEPLOY_DIR"
docker compose --env-file .env.metrics -f docker-compose.metrics.yml ps
docker compose --env-file .env.metrics -f docker-compose.metrics.yml logs --tail=30 alloy
REMOTE_VERIFY

echo ""
echo "==> VM metrics installation complete."
echo "    Remote stack directory: ${METRICS_DEPLOY_DIR}"
echo "    Local Alloy UI (remote host only): http://127.0.0.1:12345"
